import { Badge } from "@/components/ui/badge";
import { Panel } from "@/components/ui/panel";
import { MitreTable } from "@/components/MitreTable";
import type { Investigation } from "@/types/ai";

/**
 * Renders the AI analyst's report with the spec's required
 * distinction kept visually explicit: Observed Evidence (solid,
 * certain) is never styled the same as Inference (dashed border,
 * clearly marked as interpretation) — the two are never merged into
 * one undifferentiated bullet list.
 */
export function InvestigationReport({ report }: { report: Investigation }) {
  return (
    <div className="space-y-4">
      <Panel title="Executive summary">
        <p className="text-sm text-slate-200">{report.executive_summary}</p>
        <p className="text-sm text-muted mt-2">{report.what_happened}</p>
        <p className="text-xs text-muted mt-2 font-mono">{report.timeline_summary}</p>
      </Panel>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
        <Panel title="Observed evidence" className="border-signal/30">
          <ul className="space-y-1.5 text-xs text-slate-200">
            {report.observed_evidence.map((e, i) => (
              <li key={i} className="pl-3 border-l-2 border-signal/50">
                {e}
              </li>
            ))}
          </ul>
        </Panel>
        <Panel title="Inference" className="border-dashed">
          <ul className="space-y-1.5 text-xs text-slate-300 italic">
            {report.inference.map((e, i) => (
              <li key={i} className="pl-3 border-l-2 border-dashed border-line">
                {e}
              </li>
            ))}
          </ul>
        </Panel>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
        <Panel title="Affected assets">
          <div className="flex flex-wrap gap-1.5">
            {report.affected_assets.map((a) => (
              <Badge key={a} tone="neutral">
                {a}
              </Badge>
            ))}
          </div>
        </Panel>
        <Panel title="Indicators">
          <div className="flex flex-wrap gap-1.5 font-mono">
            {report.indicators.map((i) => (
              <Badge key={i} tone="neutral">
                {i}
              </Badge>
            ))}
          </div>
        </Panel>
      </div>

      <Panel title="MITRE ATT&CK mapping">
        <MitreTable techniques={report.mitre_mapping} />
      </Panel>

      <Panel title="Risk explanation">
        <p className="text-sm text-slate-200">{report.risk_explanation}</p>
      </Panel>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-4">
        <Panel title="Recommended investigation">
          <ul className="space-y-1 text-xs text-slate-200 list-disc list-inside">
            {report.recommended_investigation.map((r, i) => (
              <li key={i}>{r}</li>
            ))}
          </ul>
        </Panel>
        <Panel title="Recommended containment">
          <ul className="space-y-1 text-xs text-slate-200 list-disc list-inside">
            {report.recommended_containment.map((r, i) => (
              <li key={i}>{r}</li>
            ))}
          </ul>
        </Panel>
        <Panel title="Recommended remediation">
          <ul className="space-y-1 text-xs text-slate-200 list-disc list-inside">
            {report.recommended_remediation.map((r, i) => (
              <li key={i}>{r}</li>
            ))}
          </ul>
        </Panel>
      </div>

      <Panel title="Unknown information" className="bg-ink-800/30">
        <ul className="space-y-1 text-xs text-muted italic list-disc list-inside">
          {report.unknown_information.map((u, i) => (
            <li key={i}>{u}</li>
          ))}
        </ul>
      </Panel>

      <Panel title="Questions for human analyst">
        <ul className="space-y-1 text-xs text-slate-200 list-disc list-inside">
          {report.questions_for_analyst.map((q, i) => (
            <li key={i}>{q}</li>
          ))}
        </ul>
      </Panel>

      <p className="text-xs text-muted font-mono text-right">
        Generated by {report.generated_by} at {new Date(report.generated_at).toLocaleString()}
      </p>
    </div>
  );
}
