"""create ml_training_runs and ml_predictions tables

Revision ID: bd9c1c817bff
Revises: 15be93a4c471
Create Date: 2026-09-27 16:19:58.428653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd9c1c817bff'
down_revision: Union[str, None] = '15be93a4c471'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ml_training_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_type', sa.String(length=64), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('training_dataset', sa.String(length=255), nullable=False),
    sa.Column('num_samples', sa.Integer(), nullable=False),
    sa.Column('num_features', sa.Integer(), nullable=False),
    sa.Column('feature_names', sa.JSON(), nullable=False),
    sa.Column('contamination', sa.Float(), nullable=False),
    sa.Column('accuracy_status', sa.String(length=32), nullable=False),
    sa.Column('evaluation', sa.JSON(), nullable=False),
    sa.Column('anomalies_flagged', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_version')
    )
    op.create_table('ml_predictions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('training_run_id', sa.Integer(), nullable=False),
    sa.Column('source_ip', sa.String(length=64), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('anomaly_score', sa.Float(), nullable=False),
    sa.Column('is_anomalous', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['training_run_id'], ['ml_training_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ml_predictions_anomaly_score'), 'ml_predictions', ['anomaly_score'], unique=False)
    op.create_index(op.f('ix_ml_predictions_is_anomalous'), 'ml_predictions', ['is_anomalous'], unique=False)
    op.create_index(op.f('ix_ml_predictions_source_ip'), 'ml_predictions', ['source_ip'], unique=False)
    op.create_index(op.f('ix_ml_predictions_training_run_id'), 'ml_predictions', ['training_run_id'], unique=False)
    op.create_index(op.f('ix_ml_predictions_window_start'), 'ml_predictions', ['window_start'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ml_predictions_window_start'), table_name='ml_predictions')
    op.drop_index(op.f('ix_ml_predictions_training_run_id'), table_name='ml_predictions')
    op.drop_index(op.f('ix_ml_predictions_source_ip'), table_name='ml_predictions')
    op.drop_index(op.f('ix_ml_predictions_is_anomalous'), table_name='ml_predictions')
    op.drop_index(op.f('ix_ml_predictions_anomaly_score'), table_name='ml_predictions')
    op.drop_table('ml_predictions')
    op.drop_table('ml_training_runs')
    # ### end Alembic commands ###
