"""create incidents and incident_events, link alerts

Revision ID: e6dc5ec734c5
Revises: bd9c1c817bff
Create Date: 2026-09-28 02:45:04.643286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'e6dc5ec734c5'
down_revision: Union[str, None] = 'bd9c1c817bff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('incident_id', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('incident_type', sa.String(length=64), nullable=False),
    sa.Column('severity', postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severity', create_type=False), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('primary_username', sa.String(length=64), nullable=True),
    sa.Column('primary_source_ip', sa.String(length=64), nullable=True),
    sa.Column('primary_hostname', sa.String(length=64), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('alert_count', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_incident_id'), 'incidents', ['incident_id'], unique=True)
    op.create_index(op.f('ix_incidents_incident_type'), 'incidents', ['incident_type'], unique=False)
    op.create_index(op.f('ix_incidents_last_seen'), 'incidents', ['last_seen'], unique=False)
    op.create_index(op.f('ix_incidents_severity'), 'incidents', ['severity'], unique=False)
    op.create_index(op.f('ix_incidents_status'), 'incidents', ['status'], unique=False)
    op.create_table('incident_events',
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('incident_id', 'event_id')
    )
    op.create_index(op.f('ix_incident_events_event_id'), 'incident_events', ['event_id'], unique=False)
    op.add_column('alerts', sa.Column('incident_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_alerts_incident_id'), 'alerts', ['incident_id'], unique=False)
    op.create_foreign_key(None, 'alerts', 'incidents', ['incident_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'alerts', type_='foreignkey')
    op.drop_index(op.f('ix_alerts_incident_id'), table_name='alerts')
    op.drop_column('alerts', 'incident_id')
    op.drop_index(op.f('ix_incident_events_event_id'), table_name='incident_events')
    op.drop_table('incident_events')
    op.drop_index(op.f('ix_incidents_status'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_severity'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_last_seen'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_incident_type'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_incident_id'), table_name='incidents')
    op.drop_table('incidents')
    # ### end Alembic commands ###
